### ISSUE TITLE
Sitecore 9 support.

### ISSUE THREAD

**Issue by adomina** [heikof/RainbowCodeGeneration#4]
Could you please advise on the following issue?

I've installed Sitecore 9, Unicorn and Rainbow, items are synced. 
However, when I try to add the latest RainbowCodeGeneration to my project,
after setting up default .tt template, it fails with exception:

    Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

at the following line:

    var templates = RainbowCodeGeneration.RainbowReader.GetTemplates(physicalFileStore, treeName, treePath); 

I use the following configuration: 

    <#@ template debug="true" hostspecific="true"#>
    <#@ output extension=".cs" #>
    <#@ assembly name="System.Core" #>
    <# // NOTE - Reference your NuGet packages for Rainbow and RainbowCodeGeneration here #>
    <#@ assembly name="$(SolutionDir)packages\Rainbow.Core.2.0.0\lib\net452\Rainbow.dll" #>
    <#@ assembly name="$(SolutionDir)packages\Rainbow.Storage.Yaml.2.0.0\lib\net452\Rainbow.Storage.Yaml.dll" #>
    <#@ assembly name="$(SolutionDir)packages\RainbowCodeGeneration.0.2.0\lib\net452\RainbowCodeGeneration.dll" #>
    <# // NOTE - Reference your Sitecore.Kernel.dll and Sitecore.Logging.dll here #>
    <#@ assembly name="$(SolutionDir)\packages\Sitecore.Kernel.9.0.171002\lib\net462\Sitecore.Kernel.dll" #>
    <#@ assembly name="$(SolutionDir)\packages\Sitecore.Logging.9.0.171002\lib\net462\Sitecore.Logging.dll" #>

**Comment by heikof** [comment]
Hi @adomina 

Thanks for raising this issue. I have been able to run the Code-Gen with Sitecore 9 and Rainbow 2. You need to update some assembly references (as you have done already for Rainbow 2) and also add Microsoft.Extensions.DependencyInjection in version 1.0.0. Sitecore seems to depend on it starting in version 9. 

I have added Microsoft.Extensions.DependencyInjection v1.0.0 via NuGet and then updated my configuration as follows: 

```
<#@ template debug="false" hostspecific="true" language="C#" #>
<#@ output extension=".cs" #>
<#@ assembly name="System.Core" #>
<# // NOTE - Reference your NuGet packages for Rainbow and RainbowCodeGeneration here #>
<#@ assembly name="$(SolutionDir)packages\Rainbow.Core.2.0.0\lib\net452\Rainbow.dll" #>
<#@ assembly name="$(SolutionDir)packages\Rainbow.Storage.Yaml.2.0.0\lib\net452\Rainbow.Storage.Yaml.dll" #>
<#@ assembly name="$(SolutionDir)packages\RainbowCodeGeneration.0.2.0\lib\net452\RainbowCodeGeneration.dll" #>
<# // NOTE - Reference your Sitecore.Kernel.dll and Sitecore.Logging.dll here #>
<#@ assembly name="$(SolutionDir)packages\Sitecore.Kernel.NoReferences.9.0.171002\lib\net462\Sitecore.Kernel.dll" #>
<#@ assembly name="$(SolutionDir)packages\Sitecore.Logging.NoReferences.9.0.171002\lib\net462\Sitecore.Logging.dll" #>
<#@ assembly name="$(SolutionDir)packages\Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0\lib\netstandard1.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" #>
<#@ assembly name="$(SolutionDir)packages\Microsoft.Extensions.DependencyInjection.1.0.0\lib\netstandard1.1\Microsoft.Extensions.DependencyInjection.dll" #>
<# 
// CONFIGURATION
var physicalFileStore = @"D:\inetpub\wwwroot\sc900\Data\Unicorn"; // the path to your serialisation items
var treeName = "Feature.Sample\\Templates"; // the name of the configuration you want to code-generate 
var treePath = "/sitecore/templates/Sample"; // the matching path in Sitecore for the configuration
```

Please note that you might have to close and re-open Visual Studio or the project. T9 can be a little flaky. 

Let me know how you go and I will update the project documentation,

**Comment by heikof** [comment]
I have updated the Readme and also added example config for Sitecore 9 in v0.3 that was just released. Closing the issue, please comment/re-open if it is still a problem.

**Comment by adomina** [comment]
Many thanks, it works now
